require "insales_api/resources/base.rb"
require "insales_api/resources/account.rb"
require "insales_api/resources/category.rb"
require "insales_api/resources/client.rb"
require "insales_api/resources/collection.rb"
require "insales_api/resources/collect.rb"
require "insales_api/resources/option_name.rb"
require "insales_api/resources/option_value.rb"
require "insales_api/resources/product.rb"
require "insales_api/resources/variant.rb"
require "insales_api/resources/webhook.rb"
require "insales_api/resources/order.rb"
require "insales_api/resources/order_line.rb"
require "insales_api/resources/application_widget.rb"
require "insales_api/resources/field.rb"
require "insales_api/resources/delivery_variant.rb"
require "insales_api/resources/page.rb"

